# Production Profile Configuration
# Optimized settings for production use

api:
  # Production model settings
  models:
    defaults:
      max_tokens: 300
      temperature: 0.6
      stream: false  # Disable streaming for production
      top_p: 0.8
  
  # Client configuration for production reliability
  client:
    timeout: 25.0          # Shorter timeout for production
    max_retries: 2         # Standard retries for production
    connection_check: false # Skip health check for faster startup

logging:
  level: "WARNING"
  debug: false

ui:
  # Minimal UI output in production
  show_model_info: false
  max_history: 200

# Error handling configuration for production
error_handling:
  show_detailed_errors: false
  suggest_fixes: false
  retry_on_timeout: false

# Production storage settings
storage:
  enabled: true
  directory: "/var/lib/dmr/conversations"
  max_conversations: 10000
  auto_save: true